[package]
name = "schedule"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
chrono = "0.4"

[lib]

[dev-dependencies]
assert_cmd = "2"
pretty_assertions = "1"
predicates = "3"
#rand = "0.8"